export const state = {
  selectedCategories: [],
  searchQuery: '',
  sortBy: 'name',
  viewMode: 'grid',
  inspectorVisible: true,
  selectedAsset: null,
  selectedAssetIds: [],
  focusedAssetId: null,
  favorites: false,
  collectionIds: [],
  tagIds: [],
  libraryIds: [],
  libraries: [],
  tags: [],
  collections: [],
  assets: [],
  totalCount: 0,
  hasMore: false,
  isLoading: false
};
